name: Main workflow

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !startsWith(github.event.head_commit.message, 'docs')"
    strategy:
      matrix:
        node: ["18"]

    steps:
    - uses: actions/checkout@v4.1.7

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4.0.2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Set up Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ matrix.node }}
        cache: "npm"

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install Node.js dependencies
      run: npm ci

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
